local soluna = require("soluna")
vim.keymap.set("n", "<leader>sf", soluna.evaluate_file)
vim.keymap.set({"n", "v"}, "<leader>sl", soluna.evaluate_lines)
vim.keymap.set("n", "<leader>sc", soluna.evaluate_clear)
vim.keymap.set("n", "<leader>ss", soluna.set_input_value)
vim.keymap.set("n", "<leader>st", soluna.toggle_evaluation)
